### ISSUE TITLE
Stencil push httpt error 404

### ISSUE THREAD

**Issue by rquiros** [bigcommerce/stencil-cli#360] opened 2018-01-10 04:43 UTC
### Expected behavior
Theme should be uploaded to store

### Actual behavior
Errors out with http error 404

[user@system tir]$  stencil push
not ok -- StoreHashReadError: Response Error: 404 Not Found
Please try again. If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and submit an issue.

### Steps to reproduce behavior
Running stencil push command.

**Comment by creativewhs** [comment] 2018-01-30 15:46
I am getting this error too.
Did you find a solution?

**Comment by trendyequine** [comment] 2018-01-30 15:59
@creativewhs what template are you using? cornerstone, or a premium template?

**Comment by creativewhs** [comment] 2018-01-30 16:00
@trendyequine  It's the cornerstone template. Version 1.12.1

**Comment by DIYVaporSupply** [comment] 2018-01-30 20:34
Same
...\cornerstone>stencil push
not ok -- StoreHashReadError: Response Error: 404 Not Found
Please try again. If this error persists, please visit https://github.com/bigcom
merce/stencil-cli/issues and submit an issue.

**Comment by petrkotek** [comment] 2018-02-06 09:05
@DIYVaporSupply: what did you change in the `.stencil` file? The information look to be correct, but it still doesn't work. (The OAuth token does have modify permission `Themes:modify`)

```
{
  "normalStoreUrl": "https://mydomain.com/",
  "port": 3000,
  "clientId": "...id...",
  "accessToken": "...token...",
  "customLayouts": {
    "brand": {},
    "category": {},
    "page": {},
    "product": {}
  }
}
```

**Comment by petrkotek** [comment] 2018-02-06 09:12
can someone provide guidance? @junedkazi @mjschock //cc @aleachjr

**Comment by petrkotek** [comment] 2018-02-06 09:26
🎉  hurray, I figured out what was the problem.

The problem is a trailing slash in `normalStoreUrl` - there MUST BE NO TRAILING SLASH, only `"normalStoreUrl": "https://example.com"`.

Explanation: https://github.com/bigcommerce/stencil-cli/blob/08f6c9d8b061b239c543090abcccf2a927bb4419/lib/stencil-push.utils.js#L55 concatenates the `normalStoreUrl` with `/admin/oauth/info` and request to https://bcstore.com//admin/oauth/info` returns 404.

**Comment by aleachjr** [comment] 2018-02-06 13:12
Nice, thanks @petrkotek!

**Comment by creativewhs** [comment] 2018-02-06 19:10
Thanks @petrkotek, it works!

**Comment by DIYVaporSupply** [comment] 2018-02-06 19:48
@petrkotek
Sorry about that - My issue had been the access token. Good catch on the trailing slash.

**Comment by mjschock** [comment] 2018-02-21 00:11
fixed in https://github.com/bigcommerce/stencil-cli/pull/369

**Closed by mjschock** 2018-02-21 00:11 UTC
