### ISSUE TITLE
Unable to install stencil due to SHA issues

### ISSUE THREAD

**Issue by Bobspadger** [bigcommerce/stencil-cli#596] opened 2020-04-16 18:21 UTC
### Expected behavior
Stencil installs

### Actual behavior
Stencil fails while trying to install `node-sass 3.5.0`

### Steps to reproduce behavior

OS Catalina 10.15.4

```
➜  ~ npm -v
6.9.0
➜  ~ nvm current
v10.16.3
```

Try to install `Stencil`

`npm install -g @bigcommerce/stencil-cli`

```
16981 info lifecycle @bigcommerce/node-sass@3.5.0~prepack: @bigcommerce/node-sass@3.5.0
16982 info lifecycle @bigcommerce/node-sass@3.5.0~postpack: @bigcommerce/node-sass@3.5.0
16983 warn tarball tarball data for @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#v3.5.0 (sha1-dobpfE08NsjNIcGst/hx8n2yHWU=) seems to be corrupted. Trying one more time.
16984 info lifecycle @bigcommerce/node-sass@3.5.0~prepack: @bigcommerce/node-sass@3.5.0
16985 info lifecycle @bigcommerce/node-sass@3.5.0~postpack: @bigcommerce/node-sass@3.5.0
16986 warn tarball tarball data for @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#v3.5.0 (sha1-dobpfE08NsjNIcGst/hx8n2yHWU=) seems to be corrupted. Trying one more time.
16987 timing action:extract Completed in 23486ms
16988 verbose unlock done using /Users/alex/.npm/_locks/staging-fffdb998c3659f53.lock for /Users/alex/.nvm/versions/node/v10.16.3/lib/node_modules/.staging
16989 timing stage:rollbackFailedOptional Completed in 1ms
16990 timing stage:runTopLevelLifecycles Completed in 49955ms
16991 verbose stack Error: sha1-dobpfE08NsjNIcGst/hx8n2yHWU= integrity checksum failed when using sha1: wanted sha1-dobpfE08NsjNIcGst/hx8n2yHWU= but got sha512-Mf+zT+KCQfzQw3WY/91XVYnqhtceLCDi4DHl30ZQI+upqIHpYkITuiaCgPvR2b3EgvpAPI3nXT2ZDU7UW8S6uQ== sha1-c/anQLXkh2Vjg8SpG1hIXTD21pU=. (314072 bytes)
16991 verbose stack     at Transform.on (/Users/alex/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/ssri/index.js:328:19)
16991 verbose stack     at Transform.emit (events.js:203:15)
16991 verbose stack     at endReadableNT (_stream_readable.js:1145:12)
16991 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
16992 verbose cwd /Users/alex
16993 verbose Darwin 19.4.0
16994 verbose argv "/Users/alex/.nvm/versions/node/v10.16.3/bin/node" "/Users/alex/.nvm/versions/node/v10.16.3/bin/npm" "install" "-g" "@bigcommerce/stencil-cli"
16995 verbose node v10.16.3
16996 verbose npm  v6.9.0
16997 error code EINTEGRITY
16998 error Verification failed while extracting @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#v3.5.0:
16998 error Verification failed while extracting @bigcommerce/node-sass@git://github.com/bigcommerce-labs/node-sass.git#v3.5.0:
16998 error sha1-dobpfE08NsjNIcGst/hx8n2yHWU= integrity checksum failed when using sha1: wanted sha1-dobpfE08NsjNIcGst/hx8n2yHWU= but got sha512-Mf+zT+KCQfzQw3WY/91XVYnqhtceLCDi4DHl30ZQI+upqIHpYkITuiaCgPvR2b3EgvpAPI3nXT2ZDU7UW8S6uQ== sha1-c/anQLXkh2Vjg8SpG1hIXTD21pU=. (314072 bytes)
16999 verbose exit [ 1, true 
```

I've tried completely re-installing nvm / node etc, no joy, same issues.

**Comment by ch4ppy** [comment] 2020-08-03 22:22
Currently running into this same issue with the same versions of NPM and NVM. Is there any advice or follow ups?

**Comment by Bobspadger** [comment] 2020-08-14 17:25
I got round it using an older stencil-cli. However, now BC require 2.0.0 or above I'm back at the same issue. I need to run 2.1.1

**Comment by dcollinstw** [comment] 2020-09-18 19:51
I was getting this same error trying to upgrade the stencil-cli. On Ubuntu 18.04, after installing the libsass-dev package, the install ran successfully.

**Comment by dan-collins** [comment] 2020-09-18 19:52
I was getting this same error trying to upgrade the stencil-cli. On Ubuntu 18.04, after installing the libsass-dev package, the install ran successfully.

**Comment by junedkazi** [comment] 2020-10-09 16:50
@Bobspadger @ch4ppy can you try the latest 3.x version and confirm if the issue is resolved.

**Comment by junedkazi** [comment] 2020-10-13 17:50
@Bobspadger are you still experiencing this issue with the latest 3.x ? can we close this issue if it is no longer happening ?

**Comment by Bobspadger** [comment] 2020-10-14 13:15
@junedkazi sorry for not replying, this seems to happen on a reinstall / change of version (I'm stuck on 2.1.1 at present)

However, a simple reboot and re-attempt seems to fix this (I've had it multiple times, and uninstall, reboot , reinstall seems to fix)

**Comment by junedkazi** [comment] 2020-10-19 21:47
@Bobspadger I am going to close this one for now. Please re-open if the issue persists with cli version `3.x`

**Closed by junedkazi** 2020-10-19 21:47 UTC
