### ISSUE TITLE
stencil push --activate results in 'socket hang up' 'unknown error'

### ISSUE THREAD

**Issue by dunxtand** [bigcommerce/stencil-cli#439] opened 2019-02-08 17:03 UTC
### Expected behavior
Expected stencil push --activate to complete

### Actual behavior
I get 'socket hang up' 'unknown error'
![screen shot 2019-02-08 at 11 56 57 am](https://user-images.githubusercontent.com/12576940/52493153-c87a6a80-2b98-11e9-95ae-2b1539fbc4b9.png)

### Steps to reproduce behavior
I have a hard time reproducing because I can't tell what keeps causing this issue for me--I have one codebase that I use for six different stores, and this error has been coming up recently, seemingly without pattern. A few days ago it was happening consistently, and I switched node versions from 6.0.0 to 6.16.0, and the error stopped. But now it's been happening again with node 6.16.0.

**Comment by dunxtand** [comment] 2019-02-08 17:14
Mostly, I'm just wondering what general set of situations might be causing this error. Thank!

**Comment by dunxtand** [comment] 2019-02-08 18:43
So, I think the issue may have been caused by our deployment service automatically checking that the deployment pipeline succeeds while I tried to deploy manually. Is this the type of error that would result from starting two separate pushes at the same time?

**Comment by karen-white** [comment] 2019-02-08 19:57
Hey @dunxtand , thanks for raising this! Could you share the store URL so we can check the server logs for more info on our end? If you'd prefer not to share the URL publicly, we can connect via email at karen.white@bigcommerce.com. Thanks!

**Comment by dunxtand** [comment] 2019-02-08 21:42
Sure: wws.hickies.com, hickies-us.mybigcommerce.com, hickies-gb.mybigcommerce.com, hickies-eu.mybigcommerce.com, hickies-de.mybigcommerce.com, hickies-fr.mybigcommerce.com, and hickies-au.mybigcommerce.com. I think this has happened with all of them at some point.

**Comment by karen-white** [comment] 2019-02-08 22:12
Thanks @dunxtand ! Raising an engineering ticket to investigate, and we'll keep you posted.

**Comment by jared-shepherd** [comment] 2019-02-12 01:18
Just wanted to chime and in and say I am also experiencing this issue and provide what info I can if it might help. I downloaded our theme, changed a few strings in the config file and attempted to push it to the store via the CLI and the error showed up. I then tried to bundle the theme (which was successful) and manually upload the zip file, and it also fails. You can see the progress bar complete, then the 'Loading...' shows up (like it normally does right before the uploaded theme appears in the list) but it stays there for a really long time. I waited it out and checked the error in chrome dev tools.

CLI Error:
![stencil-cli-error-20190211-theme-upload](https://user-images.githubusercontent.com/11548321/52604650-8a8f7780-2e20-11e9-902a-a4b48e007d0e.JPG)

Manual Upload Error in Chrome Dev Tools Console:
![image](https://user-images.githubusercontent.com/11548321/52604688-ba3e7f80-2e20-11e9-9f95-c9925535c712.png)

**Comment by dunxtand** [comment] 2019-02-14 14:20
Hi, I wanted to return to this to say that I haven't seen this error in a few days. For extra context: 1) I was also getting this error when I attempted to delete themes from stores via the API, and I'm no longer getting the error in that situation, and 2) I haven't made any significant changes to my codebase that I would expect to have solved this problem.

Thanks again for your help.

**Comment by karen-white** [comment] 2019-02-14 16:32
Thanks for the follow-up @dunxtand ! Glad to hear the error has subsided.

@jared-shepherd Thanks for adding your details! Just want to make sure that the error you're experiencing is consistent with what we've been investigating. When uploading the theme in the control panel, could you check the response in the Network request tab of Chrome Dev Tools? When the theme upload completes, there's a POST request whose payload should contain an [error code](https://developer.bigcommerce.com/stencil-docs/prepare-and-upload-a-theme/troubleshooting-theme-uploads#troubleshooting-theme-uploads_error-codes) with more detail on why the theme failed to upload. Thanks!

**Comment by jared-shepherd** [comment] 2019-02-14 23:12
@karen-white I just attempted to do the manual upload again and it worked just fine. So I am not sure what the problem was but it is also working for me now as well!

**Comment by karen-white** [comment] 2019-02-14 23:13
Great news @jared-shepherd ! Thanks for the follow-up!

**Comment by junedkazi** [comment] 2019-03-29 17:39
@dunxtand @jared-shepherd since the issue is no longer happening I am going to go ahead and close this ticket. Please do re-open if the problem resurfaces.

**Closed by junedkazi** 2019-03-29 17:39 UTC
